data:
  raw_data_dir: /path/to/data/default/train
  processed_dir: /path/to/data/processed
  caption_template: "A portrait of a {label} in ancient style"

training:
  pretrained_model: /path/to/model
  output_dir: /path/to/outputs/lora6
  max_train_steps: 1000                # 总步数，按需提高
  checkpointing_steps: 1500             # 多久存一次 checkpoint
  lora_rank: 32                # 提高 rank，让残差表达能力更强
  lora_alpha: 64
  # 接着上一轮


evaluation:
  prompts:
    - "a detailed portrait of an ancient-style warrior, elegant lighting, 4k"
    - "A traditional Chinese noble"

api:
  db_path: /home/tione/notebook/lq/sd/zuoye/state/training_jobs.json
